source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'haml'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'handlebars_assets'
  gem 'libv8'
  gem 'therubyracer', platforms: :ruby
  gem 'haml_assets'
  gem 'bootstrap-sass'
  gem 'compass-rails'
  gem 'therubyracer'
  gem 'uglifier'
  gem 'rails-backbone'
end

gem 'jquery-rails'
